version: '3.8'
services:
  backend:
    build:
      context: ./backend
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ./backend:/app
      - ./mapion_scraper/output:/app/mapion_scraper/output
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

volumes:
  pg_data:
