services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: ./backend
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ./backend:/app
      - ./mapion_scraper/output:/app/mapion_scraper/output
      - ./mapion_scraper/spreadsheet:/app/mapion_scraper/spreadsheet
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - RAILS_ALLOWED_HOSTS=secoma-record.fly.dev,secoma-record.com,www.example.com

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

volumes:
  pg_data:
