# fly.toml app configuration file generated for secoma-record

app = 'secoma-record'
primary_region = 'nrt'

[build]

[deploy]
  release_command = "./bin/rails db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/'
