source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "puma", ">= 5.0"
gem "pg", "~> 1.4"
gem "devise", "~> 4.9.4"
gem "rack-cors", "~> 2.0.2"
gem "kaminari", "~> 1.2.2"
gem "bootsnap", require: false

group :development, :test do
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "dotenv-rails", "~> 3.1.7", groups: [ :development, :test ]
end
