source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "puma", ">= 5.0"
gem "pg", "~> 1.4"
gem "devise", "~> 4.9.4"
gem "devise-i18n"
gem "devise_token_auth"
gem "rack-cors", "~> 2.0.2"
gem "bootsnap", require: false
gem "active_model_serializers"
gem "actioncable"
gem 'redis'
gem 'sidekiq'
gem "sentry-ruby"
gem "sentry-rails"

group :development, :test do
  gem "brakeman", require: false
  gem "bullet"
  gem "rubocop-rails-omakase", require: false
  gem "dotenv-rails", "~> 3.1.7", groups: [ :development, :test ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "letter_opener_web"
  gem "spring-commands-rspec"
  gem 'shoulda-matchers', '~> 5.0'
end
gem "dockerfile-rails", ">= 1.7", group: :development
